### ISSUE TITLE
Uncaught non-precached-url: non-precached-url :: [{"url":"/"}]

### ISSUE THREAD

**Issue by Cluster2a** [vite-pwa/sveltekit#16]
Hey, I am getting the following error:
`Uncaught non-precached-url: non-precached-url :: [{"url":"/"}]`

I checked the _urlsToCacheKeys, and the base URL is not included.
Prerendering is completely disabled in my project.

The dev mode works fine - the problem only occurs in production mode.

```
  System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (16) x64 Intel(R) Core(TM) i9-9900KS CPU @ 4.00GHz
    Memory: 3.67 GB / 15.54 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.4.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Chrome: 107.0.5304.87
  npmPackages:
    @sveltejs/adapter-node: 1.0.0-next.100 => 1.0.0-next.100 
    @sveltejs/kit: 1.0.0-next.548 => 1.0.0-next.548 
    svelte: ^3.53.1 => 3.53.1 
    vite: ^3.2.4 => 3.2.4 
```

**Comment by userquin** [comment]
@Cluster2a can you shared your pwa plugin options?

**Comment by Cluster2a** [comment]
Hey - sure! Her you go.

```JS
SvelteKitPWA({
	srcDir: './src',
	mode: process.env.NODE_ENV as 'development' | 'production',
	strategies: 'injectManifest',
	filename: 'sw.ts',
	scope: '/',
	base: '/',
	injectRegister: 'script',
	includeAssets: ['favicon.ico', 'apple-touch-icon.png', '/img/mask-icon.svg'],
	manifest: {
		short_name: 'freispace',
		name: 'freispace',
		description: 'Your supercharged resource and project management.',
		start_url: '/dashboard?source=pwa',
		scope: '/',
		display: 'standalone',
		theme_color: '#006aa3',
		background_color: '#f3f4f6',
		icons: [
			{
				src: '/img/pwa-192x192.png',
				sizes: '192x192',
				type: 'image/png',
				purpose: 'any'
			},
			{
				src: '/img/pwa-512x512.png',
				sizes: '512x512',
				type: 'image/png',
				purpose: 'any'
			},
			{
				src: '/img/favicon.svg',
				sizes: 'any',
				type: 'image/svg+xml',
				purpose: 'any'
			}
		],
		shortcuts: [
			{
				name: 'freispace Dashboard',
				short_name: 'Dashboard',
				url: '/dashboard?source=pwa',
				icons: [
					{
						src: '/img/pwa-dashboard.png',
						type: 'image/png',
						sizes: '96x96'
					},
					{
						src: '/img/pwa-dashboard.svg',
						type: 'image/svg+xml',
						sizes: 'any'
					}
				]
			},
			{
				name: 'freispace Planner',
				short_name: 'Planner',
				url: '/planning/overview?source=pwa',
				icons: [
					{
						src: '/img/pwa-planner.png',
						type: 'image/png',
						sizes: '96x96'
					},
					{
						src: '/img/pwa-planner.svg',
						type: 'image/svg+xml',
						sizes: 'any'
					}
				]
			}
		]
	},
	injectManifest: {
		globPatterns: ['client/**/*.{js,css,ico,png,svg,webp,woff,woff2}']
	},
	devOptions: {
		enabled: true,
		type: 'module',
		navigateFallback: '/'
	}
})
```

**Comment by userquin** [comment]
@Cluster2a can you share your sw.ts?

**Comment by Cluster2a** [comment]
I am using the standard service worker.

```TS
import {
	cleanupOutdatedCaches,
	createHandlerBoundToURL,
	precacheAndRoute
} from 'workbox-precaching';
import { NavigationRoute, registerRoute } from 'workbox-routing';

declare let self: ServiceWorkerGlobalScope;

self.addEventListener('message', (event) => {
	if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();
});

// self.__WB_MANIFEST is default injection point
precacheAndRoute(self.__WB_MANIFEST);

// clean old assets
cleanupOutdatedCaches();

let allowlist: undefined | RegExp[];
if (import.meta.env.DEV) allowlist = [/^\/$/];

// to allow work offline
registerRoute(new NavigationRoute(createHandlerBoundToURL('/'), { allowlist }));
```

After removing the offline part, the service worker is working fine.

**Comment by Cluster2a** [comment]
@userquin, what if I want to use the offline mode?
Removing this is just like a workaround but not a real fix, or am I mistaken here?

**Comment by userquin** [comment]
@Cluster2a try configuring `/404` adding `+error.svelte` with prerender enabled in `+error.ts`: `export const prerender = true;`.

**Comment by Cluster2a** [comment]
![image](https://user-images.githubusercontent.com/84905165/202867175-f6bb9511-1372-4d97-b113-8fdbd3609af3.png)

![image](https://user-images.githubusercontent.com/84905165/202867189-eb1a9493-19e0-4683-9b64-7cceaf263598.png)

Do you mean like this? Doesn't work either:
![image](https://user-images.githubusercontent.com/84905165/202867204-4d6fa8b2-4339-43ca-9ff0-44b4a28859af.png)

**Comment by Cluster2a** [comment]
@userquin, ah I see - you asked for an +error.ts. This does not seem to be allowed in svelteKit:
![image](https://user-images.githubusercontent.com/84905165/202867393-2237e443-6f62-4b8c-89f3-16e8292f3b0a.png)

**Comment by userquin** [comment]
@Cluster2a try adding it at leat to the entry point (`/`: `+page.ts`), if there is no prerender we cannot fallback to any url...

**Comment by userquin** [comment]
@Cluster2a have you tried to just requets some missing page without the offline entry?

**Comment by userquin** [comment]
@Cluster2a the docs allows you to create an `error.html` under src folder, check where it is moved then use it as fallback:

https://kit.svelte.dev/docs/routing#error

![imagen](https://user-images.githubusercontent.com/6311119/202868018-026906e3-1b7e-4679-a8c8-815d5ebbbe58.png)

**Comment by Cluster2a** [comment]
I created a /sw/+page.svelte & /sw/+page.ts (prerender = true).
```TS
registerRoute(new NavigationRoute(createHandlerBoundToURL('/sw'), { allowlist }));
```
I also excluded this route from my hook.
This seems to work now.

Is this a valid way to handle this?

**Comment by Cluster2a** [comment]
I also checked the fallback error:
![image](https://user-images.githubusercontent.com/84905165/202869075-02570bc4-874d-4b7f-9fc3-b97daa05f1b3.png)
But I wasn't able to access it via URL.

**Comment by userquin** [comment]
@Cluster2a what adapter are you using? try adding the fallback to kit config file and also to kit entry in pwa options

**Comment by Cluster2a** [comment]
@userquin, i am using @sveltejs/adapter-node.
I am not aware of the fallback option. I need to check that out.

**Comment by userquin** [comment]
@Cluster2a you can check this repo:
- pwa: https://github.com/Giszmo/nostroid/blob/master/nostroid-config.js#L46
- kit: https://github.com/Giszmo/nostroid/blob/master/svelte.config.js#L15
- vite: https://github.com/Giszmo/nostroid/blob/master/vite.config.ts#L13

**Comment by Cluster2a** [comment]
@userquin, I can not use the static adapter since I am using server-side endpoints which are not supported by this adapter.

The node-adapter does not seem to accept a fallback option.

My build folder looks like this:
![image](https://user-images.githubusercontent.com/84905165/202870968-d05d7e86-6a18-4e85-b326-e23bb8ce0feb.png)

**Comment by userquin** [comment]
@Cluster2a it is using also `build` folder, and it is copying all client and prerendered folders, so we need to add a custom `manifestTransform` to the pwa plugin: just check the code in the config.ts module in this repo.

The layout is different, static-adapter will copy the client and prerendered folders contents in the build folder, adapter node will copy also the client and the prerendered to the build.

**Comment by userquin** [comment]
> The node-adapter does not seem to accept a fallback option.

Then, how the adapter serves the client assets? Maybe you only need to add a node/express middleware, when requestion `/sw` just serve the content from `prerendered/sw.html`

**Comment by Cluster2a** [comment]
> EDIT: Im think we don't need to change it, it is a problem serving assets: what is the url for `/sw`? it should be `/sw` and not `/prerendered/sw` so you need a hack to serve any generated html page.

I think you got me wrong... When requesting /sw the prerendered/sw.html is served correctly and the service worker is working.
But somehow this feels kind of hacky to create a custom pre-rendered page just for the service worker to work correctly.

**Comment by userquin** [comment]
@Cluster2a configure `/sw` in the offline route: try requesting some non existing route/page

**Comment by Cluster2a** [comment]
@userquin requesting an invalid route will bring up my error-page (404). So this seems to work.

**Comment by userquin** [comment]
> @userquin requesting an invalid route will bring up my error-page (404). So this seems to work.

try it also setting offline the browser

**Comment by Cluster2a** [comment]
@userquin, the cache seems to be messed up:
![image](https://user-images.githubusercontent.com/84905165/202871561-e2522571-aff6-40f3-908e-eaa3ff2b954f.png)
All the JS files are served directly from the /_app -Folder.
When accessing the files form cache, it somehow messes up the path:
![image](https://user-images.githubusercontent.com/84905165/202871593-fa5e0423-0c8a-48ec-8263-d7b1248d3f6b.png)

It is adding the folder of the route, which is wrong.

The cache seems good though:
![image](https://user-images.githubusercontent.com/84905165/202871615-4f02e955-c863-4ba9-a364-0d9d27955782.png)

**Comment by userquin** [comment]
@Cluster2a can you create a minimal repro?

**Comment by Cluster2a** [comment]
> @Cluster2a can you create a minimal repro?

https://github.com/Cluster2a/pwa_examle - same stuff with the wrong URLs.

**Comment by userquin** [comment]
@Cluster2a I'll check it tmr, thx

**Comment by userquin** [comment]
@Cluster2a check this commit on my fork: https://github.com/userquin/vite-pwa-kit-issue-16/commit/29fb7bc69580d34865b2e67243cf4cff6a840cf3

The main problem with this approach is the navigation pages is not being cached, so you need to refresh/visit the page twice, check and the offline support should work.

Check also the changes in the pwa options, added useCredentials and removed includeAssets adding also the exclusion of the icons in the manifest (on kit there is no need, only when using Vite)

**Comment by userquin** [comment]
@Cluster2a doing some more testing...

**Comment by iva2k** [comment]
I'm adding @vite-pwa/sveltekit to my SvelteKit template project, and I have the same issue, though I'm using adapter-static for debugging. So I stepped through the sw.js with debugger in the browser and figured out that there is a disconnect between how the urls are actually handled and how example code shows them.

If I replace:

```js
- registerRoute(new NavigationRoute(createHandlerBoundToURL('/sw'), { allowlist: [/^\/$/] }));
+ registerRoute(new NavigationRoute(createHandlerBoundToURL('prerendered/pages/sw.html'), { allowlist: [/^\/$/] }));
```

- it gets to pass this route ok.

However, it fails further down with the same error trying to cache the very first item from the manifest, and the code is complaining about url:
`/client/_app/immutable/assets/_layout-ba887965.css`

I find the same item in the precache manifest, but without the leading slash '/':

`client/_app/immutable/assets/_layout-ba887965.css`

I'm guessing that in the recent SvelteKit, @vite-pwa/sveltkit and workbox updated there were some changes that modified how the precache manifest is handled and it is all screwed up now. I will investigate a bit more.

**Comment by iva2k** [comment]
I investigated further, and concluded that SW on client is wrong place to sort out the problem. Precache manifest should be handled at build time, with manifestTransforms parameter to SvelteKitPWA plugin.

Here's version that works with adapter-static, adapter-netlify and adapter-vercel (sorry, I don't have a setup to try adapter-node):

```js
const scope = '/';

// For @sveltejs/adapter-static, @sveltejs/adapter-netlify, @sveltejs/adapter-vercel
/** @type {import('workbox-build').ManifestTransform} */
const manifestTransformStatic = async (manifestEntries) => {
  console.info('Precache Manifest Entries:');
  const manifest = manifestEntries
    .filter(
      ({ url }) =>
        // Remove paths that should not be cached:
        url !== 'client/vite-manifest.json' && url !== 'prerendered/fallback.html'
      // && url !== 'client/manifest.webmanifest' && !url.endsWith('sw.js') && !url.startsWith('workbox-')
    )
    .map((e) => {
      // Adjust paths to match what the adapter server understands:
      const url1 = e.url;
      let url = e.url;
      if (url.startsWith('/')) url = url.slice(1);
      if (url.startsWith('client/')) url = url.slice(7);
      if (url.startsWith('prerendered/pages/')) url = url.slice(18);

      // router paths
      if (url && url.endsWith('.html')) {
        url = url === 'index.html' ? '' : `${url.substring(0, url.lastIndexOf('.'))}`;
      }
      e.url = scope + url; // Canonical URL starts with base
      console.info(`  ${url1.padEnd(100)} => ${JSON.stringify(e)}`);
      return e;
    });
  return { manifest };
};
const manifestTransforms = [manifestTransformStatic];
```

Pass `manifestTransforms` to SvelteKitPWA.

**Comment by iva2k** [comment]
I also checked source of `@vite-pwa/sveltekit`, and found it sets default `manifestTransforms` by `createManifestTransform()` which does pretty much the same as what I posted above in `manifestTransformStatic()`, with `createManifestTransform()` handling settings more thoroughly.

The reason it was not working in my case, is I had `manifestTransforms` set to a non-transform, just to log the precache manifest.

So for the `adapter-node` - it server static, client and prerender. Note that adapter-static serves prerender/pages, which means adapter-node will have `/page/index.html`, not `/index.html`. Default `createManifestTransform()` does not handle that case. The quick fix could be to use my `manifestTransformStatic()` and adjust the paths until they match what adapter-node serves.

BTW, `createManifestTransform()` might emit precache manifest with a duplicate entry, if `fallback` is set to `index.html`. Just note that it is a special case and handle it accordingly - precache manifest is created from list of paths found in `./.svelte-kit/output/client`, and transformManifest should emit the list of paths matching what is served by the adapter.

**Comment by userquin** [comment]
@iva2k thx for investigating this, I have it pending,  maybe we can add some presets, pr welcome

**Comment by userquin** [comment]
@kyllerss pwa plugin is just a wrapper for workbox-build, that is  file based, that's, to generate the sw precache manifest (injection point/self.__WB_MANIFEST), and so kit integration will configure pwa plugin to run after prerender but before adapter processes in kit/vite lifecycle.

Once prerender finish, pwa plugin will call workbox-build to generate the sw precache manifest: we need to configure pwa plugin properly via `globDirectory` on `workbox` or `injectManifest` : workbox-build will use `globDirectory` to traverse it and generate the sw in the sw with the sw precache manifest. We also need to configure properly the output folder, that's, the sw.js should be generated in the kit output build folder, that adapter will copy to the final build folder.

Once we have configured the pwa plugin, we can add some hooks to workbox-build before sw.js is written to disk: kit integration adds a ManifestTransform (will receive file paths in globDirectory and their revision/hash, a list of ManifestEntry objects) to apply some custom transformations (pretty url and fallback url for adapter). You can check it here, the config module has a few comments about kit output folder: https://github.com/vite-pwa/sveltekit/blob/main/src/config.ts#L60

With latest `vite-plugin-pwa` version released `0.14.0` (kit integration not updated nor released yet) we can use custom sw without injection point (I also need to update the docs to add this new option).

**Comment by iva2k** [comment]
@userquin
> thx for investigating this, I have it pending, maybe we can add some presets, pr welcome

I'd like to submit a PR, but the scope is unclear...

I'm thinking that best design would be to have `createManifestTransform()` coordinate with the adapter, maybe just get a map (source file -> URL destination) from the adapter and use that map, or adapter should provide the transform function, since it only knows how things will be on the server.

Another improvement is to expose / export createManifestTransform(), and allow caller to compose their array of transforms and invoke the standard one which came from the adapter in their chain. That way adapter will have a say, and custom transform added before or after can act on URLs (post) or on file paths (pre), and won't need to know how things are mapped.

Right now custom transform should know what the adapter does, but it has no context to get which adapter is used. In case of adapter-auto, there are few possible actual adapters that custom transform has to figure out. And users could make their own custom adapters. Extending adapter scope will go into `sveltejs/kit` repo. If that PR is rejected, there's no way to make an informed transform.

**Comment by userquin** [comment]
@iva2k if you provide a custom TransformManifest the plugin will no register the default one. We can add some preset folder adding there the required stuff, maybe also adding some custom configuration options, not only the TransformManifest:

https://github.com/vite-pwa/sveltekit/blob/main/src/config.ts#L56

**Comment by iva2k** [comment]
@userquin 
>if you provide a custom TransformManifest the plugin will no register the default one

Yes. What I'm saying is if I can call `createManifestTransform()` and get the default transform, I could use it in my chain and do this:

```js
  const myPreTransform = (manifest) => {... my file transforms; return manifest; }
  const myPostTransform = (manifest) => {... my URL transforms; return manifest; }
  const defaultTransform = createManifestTransform();
  const transforms = [
    myPreTransform,
    defaultTransform,
    myPostTransform 
  ];
```

Then just pass `transforms` to the plugin.

**Comment by userquin** [comment]
@iva2k oh yeah, maybe we can add `preManifestTransform` and `postManifestTransform` options to the kit entry with the following logic:
- if `manifestTransform` not empty, then unshift `preManifestTransform` and add `postManifestTransform`
- if `manifestTransform` not configured or empty then add `preManifestTransform`, then add default one and finally add `postManifestTransform`

We can also  export `createManifestTransform`: I guess we can also add default presets for adapters (if needed).

**Comment by kyllerss** [comment]
Hi, checking in. Is the fix for this one on the roadmap or is there some workaround I should be applying in the meantime (wasn't clear from the comments). Thanks!

**Comment by stellanhaglund** [comment]
I'm also getting this issue with the default config provided in the docs  and using adapter-auto, seems like it's preventing the service-worker to install in safari

**Comment by userquin** [comment]
check #30 we've detected a bug in custom manifest transform, should be fixed once new version released, in the meantime try adding the manifest transform in the PR to your `workbox: { manifestTransform: [] }` or `injectManifest: { manifestTransform: [] }` array depending on the strategy used.

**Comment by ESchouten** [comment]
So has this issue been resolved? And if so, is there a guide or demo project I can follow? The above discussion does not seem to solve my iasue. I can't seem to get the offline caching of the pages working, receiving the error `Uncaught non-precached-url: non-precached-url :: [{"url":"/"}]` when deployed to Vercel.

I want to purely store the application in cache and nothing else, the webapp can just make http requests which will be handled by the service workers.

**Comment by ktecho** [comment]
This is also failing for me. I'll try the SvelteKit suplied service worker, but it would be cool to have a bit notice saying `vite-pwa` doesn't work in SvelteKit if you're using adapter-node` so we don't lose so much time trying to guess what happens.

**Comment by ESchouten** [comment]
@nadanke @ktecho  Yes, that's what I am doing now, I am using the Workbox libraries and use these functions directly in the Sveltekits serice-worker.ts.
But since VitePWA advertises with being zero-config, I was hoping the caching & offline working part of PWAs would be automatically solved for my application.

**Comment by userquin** [comment]
closed via #32

**Comment by phil-w** [comment]
Yeah I'm getting this too, not sure what it's about as I have a path / and it works fine, so I can't see why it'd whine about it.

**Comment by userquin** [comment]
@phil-w You need to prerender that route, workbox requires the html file, check if the index.html is present in your kit output folder, inside prerender folder

**Comment by phil-w** [comment]
Ah, thanks, copy that.
